from __future__ import annotations

import getpass
import os
import platform
import subprocess
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
VENV_DIR = PROJECT_DIR / ".venv"
ENV_FILE = PROJECT_DIR / ".env"
MIN_PYTHON = (3, 10)


def run(cmd, check=True, capture=False):
    print("\n> " + " ".join(f'"{x}"' if " " in str(x) else str(x) for x in cmd))
    return subprocess.run(
        [str(x) for x in cmd],
        cwd=str(PROJECT_DIR),
        check=check,
        text=True,
        capture_output=capture,
    )


def fail(message):
    print("\n[SETUP ERROR]\n" + message)
    raise SystemExit(1)


def venv_python():
    return VENV_DIR / ("Scripts/python.exe" if os.name == "nt" else "bin/python")


def check_python():
    if sys.version_info < MIN_PYTHON:
        fail(
            f"JEEV requires Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]} or newer. "
            f"Detected {sys.version.split()[0]}."
        )


def create_venv():
    py = venv_python()
    if py.exists():
        print("[OK] Existing .venv found.")
        return py

    print("[SETUP] Creating .venv...")
    run([sys.executable, "-m", "venv", str(VENV_DIR)])
    if not py.exists():
        fail(f"Could not create virtual environment: {py}")
    print("[OK] .venv created.")
    return py


def pip(py, *args):
    return run([py, "-m", "pip", *args])


def install_requirements(py):
    files = sorted(PROJECT_DIR.glob("requirements*.txt"))

    req_dir = PROJECT_DIR / "requirements"
    if req_dir.is_dir():
        files += sorted(req_dir.glob("*.txt"))

    unique = []
    seen = set()
    for f in files:
        key = str(f.resolve()).casefold()
        if f.is_file() and key not in seen:
            seen.add(key)
            unique.append(f)

    if not unique:
        print("[WARNING] No requirements*.txt files found.")
        return

    print("\n[SETUP] Installing all requirements files:")
    for f in unique:
        print("  -", f.relative_to(PROJECT_DIR))
        pip(py, "install", "-r", f)

    print("[OK] All requirements installed.")


def read_env():
    values = {}
    if not ENV_FILE.exists():
        return values

    text = ENV_FILE.read_text(encoding="utf-8-sig")
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            value = value[1:-1]
        values[key.strip()] = value
    return values


def write_env(values):
    lines = [
        "# JEEV MARK I environment configuration",
        "# Generated by setup.py",
        "",
    ]

    for key, value in values.items():
        value = str(value).replace("\r", "").replace("\n", "")
        lines.append(f"{key}={value}")

    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")


def configure_api():
    env = read_env()
    existing = env.get("OPENROUTER_API_KEY", "").strip()

    if existing:
        print("[OK] OPENROUTER_API_KEY already exists in .env.")
        return

    print("\n" + "=" * 68)
    print("JEEV API SETUP")
    print("=" * 68)
    print("Only the OpenRouter API key is required by this installer.")
    print(f"The key will be stored locally in: {ENV_FILE}")
    print("The .env file should NOT be committed to GitHub.")
    print()

    try:
        key = getpass.getpass("Enter your OpenRouter API key: ").strip()
    except (KeyboardInterrupt, EOFError):
        print()
        fail("API key entry cancelled.")

    if not key:
        fail("No OpenRouter API key was entered.")

    env["OPENROUTER_API_KEY"] = key
    write_env(env)
    print("[OK] .env configured.")


def syntax_check(py):
    print("\n[SETUP] Running Python syntax check...")
    result = run(
        [py, "-m", "compileall", "-q", str(PROJECT_DIR)],
        check=False,
        capture=True,
    )

    if result.returncode:
        print(result.stdout or "")
        print(result.stderr or "")
        fail("Python syntax check failed.")

    print("[OK] Python syntax check passed.")


def main():
    print("=" * 68)
    print("                 JEEV MARK I SETUP")
    print("=" * 68)
    print("Project:", PROJECT_DIR)
    print("OS:", platform.system(), platform.release())
    print("Python:", sys.version.split()[0])
    print("=" * 68)

    check_python()

    py = create_venv()

    print("\n[SETUP] Updating pip/setuptools/wheel...")
    pip(py, "install", "--upgrade", "pip", "setuptools", "wheel")

    install_requirements(py)
    configure_api()
    syntax_check(py)

    main_file = PROJECT_DIR / "main.py"

    print("\n" + "=" * 68)
    print("JEEV SETUP COMPLETE")
    print("=" * 68)
    print("Virtual environment:", VENV_DIR)
    print("Environment file:", ENV_FILE)
    print("All discovered requirements have been installed.")
    print("=" * 68)

    if main_file.exists():
        answer = input("\nStart JEEV now? [Y/n]: ").strip().lower()
        if answer in ("", "y", "yes"):
            print("\nStarting JEEV MARK I...\n")
            os.execv(str(py), [str(py), str(main_file)])

    print("\nJEEV is installed and ready.")


if __name__ == "__main__":
    main()
