from __future__ import annotations

import getpass
import os
import platform
import re
import subprocess
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parent
VENV_DIR = PROJECT_DIR / ".venv"
ENV_FILE = PROJECT_DIR / ".env"
MIN_PYTHON = (3, 10)

API_SPECS = [
    {"canonical":"OPENROUTER_API_KEY","label":"OpenRouter API key","description":"JEEV AI conversation, routing and coding-agent features.","aliases":["OPENROUTER_API_KEY","OPENROUTER_KEY"]},
    {"canonical":"GOOGLE_API_KEY","label":"Google API key","description":"Google/Gemini functionality used by JEEV.","aliases":["GOOGLE_API_KEY","GEMINI_API_KEY"]},
    {"canonical":"QWEN_IMAGE_API_KEY","label":"Qwen Image API key","description":"Qwen image-generation functionality.","aliases":["QWEN_IMAGE_API_KEY","QWEN_API_KEY","HF_TOKEN","HUGGINGFACEHUB_API_TOKEN"]},
]

def run(cmd, check=True, capture=False):
    print("\n> " + " ".join(f'"{x}"' if " " in str(x) else str(x) for x in cmd))
    return subprocess.run([str(x) for x in cmd], cwd=str(PROJECT_DIR), check=check, text=True, capture_output=capture)

def fail(message):
    print("\n[SETUP ERROR]\n" + message)
    raise SystemExit(1)

def venv_python():
    return VENV_DIR / ("Scripts/python.exe" if os.name == "nt" else "bin/python")

def check_python():
    if sys.version_info < MIN_PYTHON:
        fail(f"JEEV requires Python {MIN_PYTHON[0]}.{MIN_PYTHON[1]} or newer. Detected {sys.version.split()[0]}.")

def create_venv():
    py = venv_python()
    if py.exists():
        print("[OK] Existing .venv found.")
        return py
    print("[SETUP] Creating .venv...")
    run([sys.executable, "-m", "venv", str(VENV_DIR)])
    if not py.exists():
        fail(f"Could not create virtual environment: {py}")
    print("[OK] .venv created.")
    return py

def pip(py, *args):
    return run([py, "-m", "pip", *args])

def find_requirements():
    files = list(PROJECT_DIR.glob("requirements*.txt"))
    req_dir = PROJECT_DIR / "requirements"
    if req_dir.is_dir():
        files += list(req_dir.glob("*.txt"))
    unique, seen = [], set()
    for f in sorted(files):
        key = str(f.resolve()).casefold()
        if f.is_file() and key not in seen:
            seen.add(key)
            unique.append(f)
    return unique

def install_requirements(py):
    files = find_requirements()
    if not files:
        print("[WARNING] No requirements*.txt files found.")
        return
    print("\n[SETUP] Installing all requirements files:")
    for f in files:
        print("  -", f.relative_to(PROJECT_DIR))
        pip(py, "install", "-r", f)
    print("[OK] All requirements installed.")

def read_env():
    values = {}
    if not ENV_FILE.exists():
        return values
    text = ENV_FILE.read_text(encoding="utf-8-sig")
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, value = line.split("=", 1)
        value = value.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in '\"\'':
            value = value[1:-1]
        values[key.strip()] = value
    return values

def write_env(values):
    lines = ["# JEEV MARK I environment configuration", "# Generated by setup.py", "# KEEP THIS FILE PRIVATE.", "# DO NOT COMMIT API KEYS TO GITHUB.", ""]
    for key, value in values.items():
        value = str(value).replace("\r", "").replace("\n", "")
        lines.append(f"{key}={value}")
    ENV_FILE.write_text("\n".join(lines) + "\n", encoding="utf-8")

def valid(value):
    if value is None:
        return False
    value = str(value).strip()
    return bool(value) and value.casefold() not in {"your_api_key","your_api_key_here","your_key_here","paste_key_here","change_me","changeme","replace_me","none","null"}

def find_value(env, aliases):
    for name in aliases:
        if valid(env.get(name)):
            return str(env[name]).strip(), name
    for name in aliases:
        if valid(os.environ.get(name)):
            return os.environ[name].strip(), name
    return None, None

def scan_project():
    detected = set()
    patterns = [
        re.compile(r'''os\.getenv\(\s*["']([A-Z][A-Z0-9_]*)["']'''),
        re.compile(r'''os\.environ\.get\(\s*["']([A-Z][A-Z0-9_]*)["']'''),
        re.compile(r'''os\.environ\s*\[\s*["']([A-Z][A-Z0-9_]*)["']\s*\]'''),
        re.compile(r'''environ\.get\(\s*["']([A-Z][A-Z0-9_]*)["']'''),
    ]
    ignored = {"PATH","HOME","TEMP","TMP","USERNAME","USERPROFILE","SYSTEMROOT","PROGRAMFILES","APPDATA","LOCALAPPDATA","COMPUTERNAME","VIRTUAL_ENV"}
    for path in PROJECT_DIR.rglob("*.py"):
        if any(part in {".venv",".git","__pycache__"} for part in path.parts):
            continue
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        for pattern in patterns:
            for match in pattern.finditer(text):
                if match.group(1) not in ignored:
                    detected.add(match.group(1))
    return detected

def configure_api():
    env = read_env()
    detected = scan_project()
    print("\n[SETUP] Detected environment variables:")
    for name in sorted(detected):
        print("  -", name)
    changed = False
    print("\n" + "=" * 68)
    print("JEEV API SETUP")
    print("=" * 68)
    print("Existing .env/system variables are reused. Only missing keys are requested.")
    for spec in API_SPECS:
        value, source = find_value(env, spec["aliases"])
        if value:
            if spec["canonical"] not in env:
                env[spec["canonical"]] = value
                changed = True
            print(f"[READY] {spec['canonical']}" + (f" (found as {source})" if source != spec["canonical"] else ""))
            continue
        print(f"\n{spec['label']}\n{spec['description']}")
        try:
            value = getpass.getpass(f"Enter {spec['label']}: ").strip()
        except (KeyboardInterrupt, EOFError):
            print()
            fail("API key entry cancelled.")
        if not value:
            fail(f"No {spec['canonical']} key was entered.")
        env[spec["canonical"]] = value
        changed = True
        print(f"[OK] {spec['canonical']} configured.")
    if changed or not ENV_FILE.exists():
        write_env(env)
        print(f"[OK] .env saved: {ENV_FILE}")

def protect_env():
    gitignore = PROJECT_DIR / ".gitignore"
    existing = gitignore.read_text(encoding="utf-8").splitlines() if gitignore.exists() else []
    changed = False
    for entry in [".env",".venv/","__pycache__/"]:
        if entry not in existing:
            existing.append(entry)
            changed = True
    if changed:
        gitignore.write_text("\n".join(existing) + "\n", encoding="utf-8")
        print("[OK] .gitignore protects .env/.venv.")

def syntax_check(py):
    print("\n[SETUP] Running Python syntax check...")
    result = run([py, "-m", "compileall", "-q", str(PROJECT_DIR)], check=False, capture=True)
    if result.returncode:
        print(result.stdout or "")
        print(result.stderr or "")
        fail("Python syntax check failed.")
    print("[OK] Python syntax check passed.")

def main():
    print("=" * 68)
    print("                 JEEV MARK I SETUP")
    print("=" * 68)
    print("Project:", PROJECT_DIR)
    print("OS:", platform.system(), platform.release())
    print("Python:", sys.version.split()[0])
    print("=" * 68)
    check_python()
    py = create_venv()
    print("\n[SETUP] Updating pip/setuptools/wheel...")
    pip(py, "install", "--upgrade", "pip", "setuptools", "wheel")
    install_requirements(py)
    configure_api()
    protect_env()
    syntax_check(py)
    main_file = PROJECT_DIR / "main.py"
    print("\n" + "=" * 68)
    print("JEEV SETUP COMPLETE")
    print("=" * 68)
    print("Virtual environment:", VENV_DIR)
    print("Environment file:", ENV_FILE)
    print("Dependencies: INSTALLED")
    print("API configuration: READY")
    print("Syntax: PASSED")
    print("=" * 68)
    if main_file.exists():
        try:
            answer = input("\nStart JEEV now? [Y/n]: ").strip().lower()
        except (KeyboardInterrupt, EOFError):
            answer = "n"
        if answer in ("", "y", "yes"):
            print("\nStarting JEEV MARK I...\n")
            os.execv(str(py), [str(py), str(main_file)])
    print("\nJEEV is installed and ready.")

if __name__ == "__main__":
    main()
